using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SAMLSPLib
{
    public class SAMLSettings
    {
        public static string certificate = "MIIE4DCCA8igAwIBAgIQbfh5VVE7ej/WG25F2q9daTANBgkqhkiG9w0BAQUFADA8MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMVGhhd3RlLCBJbmMuMRYwFAYDVQQDEw1UaGF3dGUgU1NMIENBMB4XDTE0MDUxNDAwMDAwMFoXDTE4MDUxMzIzNTk1OVowgacxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpRdWVlbnNsYW5kMRQwEgYDVQQHFAtCb3dlbiBIaWxsczEzMDEGA1UEChQqVklSR0lOIEFVU1RSQUxJQSBBSVJMSU5FUyBIT0xESU5HUyBQVFkgTFREMRYwFAYDVQQLFA1JVCBEZXBhcnRtZW50MSAwHgYDVQQDFBdpZHAudmlyZ2luYXVzdHJhbGlhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALdpic70r96tIK2qEOEdsvV/uZUv3Ok2skBpejh3lihu30lgsluM9HmzmVQKqz67raTdQvCUMvwrgPUTGv+ISuo0cNJevQs5XB8LgtGgdztcFB2FiUfeOYgz0CwskWcfl/aRhtQn+4iamCO6Jj7uPinC2+wYOI7aFzj6IPQMwEP2oxwJQSP91d5W7OFVAG4P+Py7ZtElELrgOYd0v4GXw76XCRTqqcCboDHpV4DPX9vHXDgdvv3vE8l4IGe6K6rlz0KrPijxiT1oN8vIH6oRph6DUgLG7QcCl5eFRH83gUR+zX0fxlRBZC9TMe5UpCkQY3tGrnx4d8FUPV5tIe9aAsMCAwEAAaOCAXAwggFsMCIGA1UdEQQbMBmCF2lkcC52aXJnaW5hdXN0cmFsaWEuY29tMAkGA1UdEwQCMAAwZQYDVR0gBF4wXDBaBgpghkgBhvhFAQc2MEwwIwYIKwYBBQUHAgEWF2h0dHBzOi8vZC5zeW1jYi5jb20vY3BzMCUGCCsGAQUFBwICMBkWF2h0dHBzOi8vZC5zeW1jYi5jb20vcnBhMA4GA1UdDwEB/wQEAwIFoDAfBgNVHSMEGDAWgBSnooO7NEVAPfzVME8SuT6hAZ/22zArBgNVHR8EJDAiMCCgHqAchhpodHRwOi8vdGIuc3ltY2IuY29tL3RiLmNybDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUFBzABhhNodHRwOi8vdGIuc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8vdGIuc3ltY2IuY29tL3RiLmNydDANBgkqhkiG9w0BAQUFAAOCAQEAbsnuVEXFm7maESqtNTN6nXSibIWcKEEMBlLaYx0peMgjlH/qFlL8aO4ri8tFR0dzvSfiCaI5xYEE0rV66bCCDjDf7vFpUHPaNcJ0bkQFc9Uniq6d+f2KYJIBS5E7hgh1Gl5a3jJAoOQhHAsfuj/7/UNYwJrVcWv2Ab7J8GkYfFoGmU9BjSe/dBOa/zGy0hDQ80lKeDarSDo+gUZwospAwWVzuPxOxIMLjA3KwtWYyl7bUCv3szZS4Pu6sBRu39UdWDtLnb3PK34bfxVXk4/GRMKgDPVgns3uFRlqgEN1pXYcg7PBKDDIWj7p1oK0d4pk4jIWz5jUmVu+MPZPJV8kRw==";
        public static string assertionConsumerServiceUrl = "http://example.org/samlassertionconsumer";    
        public static string issuer = "http://example.org/samlassertionconsumer";      
        public static string idp_sso_target_url = "https://targetidp.org/sso";
        public static string idp_logout_target_url = "https://targetidp.org/logout";

    }
}
